spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create  # 스키마 자동 생성
    show-sql: true      # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL pretty print
  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            scope:
              - email
              - profile
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

#AWS S3
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: bobimage
    stack:
      auto-: false
    region:
      static: ap-northeast-2

mail:
  address:
    admin: admin@gmail.com 

jwt:
  key:
    secret: bobfriend132412341234123412341234123423412341234123412341234114123411234123412341234
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420
