name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ] 

permissions:
  contents: read
  
env:
  S3_BUCKET_NAME: bobfriends-s3-bucket

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server/bf

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    # application-server.yml 설정
    - name: Set Yaml
      uses: microsoft/variable-substitution@v1
      with:
       files: ./server/bf/src/main/resources/application-server.yml
      env:
       spring.datasource.password: ${{ secrets.MYSQL_PASSWORD }}
       spring.datasource.username: ${{ secrets.MYSQL_USERNAME }}
       
       cloud.aws.credentials.accessKey: ${{ secrets.AWS_ACCESS_KEY }}
       cloud.aws.credentials.secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       
       jwt.key.secret: ${{ secrets.JWT_SECRET_KEY }}
       
       spring.security.oauth2.client.registration.google.clientId: ${{ secrets.GOOGLE_CLIENT_ID }}
       spring.security.oauth2.client.registration.google.clientSecret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
       
    - name: init with Gradle
      uses: gradle/gradle-build-action@v2
    - run: gradle init

    - name: Grant execute permissions to gradlew script
      run: chmod +x ./server/bf/gradlew
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    
    # build한 후 프로젝트를 압축합니다.
    - name: Make zip file
      run: zip -r ./bobfriends-deploy.zip .
      shell: bash
    
    # Access Key와 Secret Access Key를 통해 권한을 확인합니다.
    # 아래 코드에 Access Key와 Secret Key를 직접 작성하지 않습니다.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }} # 등록한 Github Secret이 자동으로 불려옵니다.
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # 등록한 Github Secret이 자동으로 불려옵니다.
        aws-region: ap-northeast-2
    
    # 압축한 프로젝트를 S3로 전송합니다.
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./bobfriends-deploy.zip s3://$S3_BUCKET_NAME/bobfriends-deploy.zip
      
    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name my-codedeploy-app
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name my-codedeploy-deployment-app
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=bobfriends-deploy.zip
